apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matrix

resources:
- secrets.yaml
- prosody.yaml
- jicofo.yaml
- jvb.yaml
- web.yaml
- web-config.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: jitsi-meet
  app.kubernetes.io/instance: jitsi-meet
  app.kubernetes.io/managed-by: kustomize
